version: "3.7"
services:
  app:
    build:
      context: ./backend/
    restart: unless-stopped
    ports:
      - 3333:3333
  
  front: 
    build:
      context: ./frontend/
    restart: unless-stopped
    ports:
      - 3000:3000

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_news
